/**
 * API Documentation generator.
 * Converts collections + saved requests into clean Markdown documentation.
 */

export interface DocEndpoint {
  method: string;
  url: string;
  name: string;
  description?: string;
  headers?: Record<string, string>;
  params?: Record<string, string>;
  body?: string;
  bodyType?: string;
  exampleResponse?: string;
}

export interface DocSection {
  name: string;
  description?: string;
  endpoints: DocEndpoint[];
}

export interface GeneratedDoc {
  markdown: string;
  html: string;
  endpointCount: number;
  sectionCount: number;
}

/**
 * Generate Markdown documentation from doc sections.
 */
export function generateMarkdown(
  title: string,
  description: string,
  baseUrl: string,
  sections: DocSection[]
): string {
  const lines: string[] = [];

  lines.push(`# ${title}`);
  lines.push('');
  if (description) {
    lines.push(description);
    lines.push('');
  }
  if (baseUrl) {
    lines.push(`**Base URL:** \`${baseUrl}\``);
    lines.push('');
  }

  lines.push('---');
  lines.push('');

  // Table of contents
  lines.push('## Table of Contents');
  lines.push('');
  sections.forEach((section, si) => {
    lines.push(`${si + 1}. [${section.name}](#${slugify(section.name)})`);
    section.endpoints.forEach((ep, ei) => {
      lines.push(`   ${si + 1}.${ei + 1}. [${ep.method} ${ep.name}](#${slugify(`${ep.method}-${ep.name}`)})`);
    });
  });
  lines.push('');
  lines.push('---');
  lines.push('');

  // Sections
  sections.forEach((section) => {
    lines.push(`## ${section.name}`);
    lines.push('');
    if (section.description) {
      lines.push(section.description);
      lines.push('');
    }

    section.endpoints.forEach((ep) => {
      lines.push(`### ${ep.method} ${ep.name}`);
      lines.push('');
      if (ep.description) {
        lines.push(ep.description);
        lines.push('');
      }

      // Method + URL
      lines.push('```');
      lines.push(`${ep.method} ${ep.url}`);
      lines.push('```');
      lines.push('');

      // Headers
      if (ep.headers && Object.keys(ep.headers).length > 0) {
        lines.push('**Headers:**');
        lines.push('');
        lines.push('| Header | Value |');
        lines.push('|--------|-------|');
        for (const [key, value] of Object.entries(ep.headers)) {
          lines.push(`| \`${key}\` | \`${value}\` |`);
        }
        lines.push('');
      }

      // Query Parameters
      if (ep.params && Object.keys(ep.params).length > 0) {
        lines.push('**Query Parameters:**');
        lines.push('');
        lines.push('| Parameter | Value |');
        lines.push('|-----------|-------|');
        for (const [key, value] of Object.entries(ep.params)) {
          lines.push(`| \`${key}\` | \`${value}\` |`);
        }
        lines.push('');
      }

      // Request Body
      if (ep.body) {
        lines.push(`**Request Body** (\`${ep.bodyType || 'json'}\`):`);
        lines.push('');
        lines.push('```json');
        lines.push(tryPrettyJson(ep.body));
        lines.push('```');
        lines.push('');
      }

      // Example Response
      if (ep.exampleResponse) {
        lines.push('**Example Response:**');
        lines.push('');
        lines.push('```json');
        lines.push(tryPrettyJson(ep.exampleResponse));
        lines.push('```');
        lines.push('');
      }

      lines.push('---');
      lines.push('');
    });
  });

  // Footer
  lines.push(`> Generated by API-Watch on ${new Date().toLocaleDateString()}`);

  return lines.join('\n');
}

/**
 * Convert Markdown to simple HTML.
 */
export function markdownToHtml(md: string): string {
  let html = md;

  // Headings
  html = html.replace(/^### (.+)$/gm, '<h3>$1</h3>');
  html = html.replace(/^## (.+)$/gm, '<h2>$1</h2>');
  html = html.replace(/^# (.+)$/gm, '<h1>$1</h1>');

  // Bold
  html = html.replace(/\*\*(.+?)\*\*/g, '<strong>$1</strong>');

  // Inline code
  html = html.replace(/`([^`]+)`/g, '<code>$1</code>');

  // Code blocks
  html = html.replace(/```(\w*)\n([\s\S]*?)```/g, (_match, lang, code) => {
    return `<pre><code class="language-${lang}">${escapeHtml(code.trim())}</code></pre>`;
  });

  // Tables
  html = html.replace(/^\|(.+)\|$/gm, (match) => {
    const cells = match.split('|').filter((c) => c.trim()).map((c) => c.trim());
    if (cells.every((c) => /^-+$/.test(c))) return ''; // separator row
    const tag = 'td';
    return `<tr>${cells.map((c) => `<${tag}>${c}</${tag}>`).join('')}</tr>`;
  });

  // Horizontal rules
  html = html.replace(/^---$/gm, '<hr>');

  // Blockquotes
  html = html.replace(/^> (.+)$/gm, '<blockquote>$1</blockquote>');

  // List items
  html = html.replace(/^\d+\.\s+(.+)$/gm, '<li>$1</li>');

  // Paragraphs (lines that are not already HTML)
  html = html.replace(/^(?!<[a-z]|$)(.+)$/gm, '<p>$1</p>');

  // Clean up empty lines
  html = html.replace(/\n{2,}/g, '\n');

  // Wrap in styled container
  return `<!DOCTYPE html>
<html lang="en">
<head>
<meta charset="UTF-8">
<meta name="viewport" content="width=device-width, initial-scale=1.0">
<title>API Documentation</title>
<style>
  body { font-family: -apple-system, BlinkMacSystemFont, 'Segoe UI', sans-serif; max-width: 900px; margin: 0 auto; padding: 40px 20px; color: #1a1a2e; line-height: 1.6; }
  h1 { color: #0f172a; border-bottom: 2px solid #e2e8f0; padding-bottom: 12px; }
  h2 { color: #1e293b; margin-top: 32px; }
  h3 { color: #334155; }
  code { background: #f1f5f9; padding: 2px 6px; border-radius: 4px; font-size: 0.9em; }
  pre { background: #0f172a; color: #e2e8f0; padding: 16px; border-radius: 8px; overflow-x: auto; }
  pre code { background: none; color: inherit; padding: 0; }
  table { border-collapse: collapse; width: 100%; margin: 12px 0; }
  td, th { border: 1px solid #e2e8f0; padding: 8px 12px; text-align: left; }
  tr:nth-child(even) { background: #f8fafc; }
  hr { border: none; border-top: 1px solid #e2e8f0; margin: 24px 0; }
  blockquote { border-left: 4px solid #3b82f6; margin-left: 0; padding: 8px 16px; color: #64748b; background: #f8fafc; }
</style>
</head>
<body>
${html}
</body>
</html>`;
}

/**
 * Generate full documentation from sections.
 */
export function generateDocumentation(
  title: string,
  description: string,
  baseUrl: string,
  sections: DocSection[]
): GeneratedDoc {
  const endpointCount = sections.reduce((sum, s) => sum + s.endpoints.length, 0);
  const markdown = generateMarkdown(title, description, baseUrl, sections);
  const html = markdownToHtml(markdown);

  return {
    markdown,
    html,
    endpointCount,
    sectionCount: sections.length,
  };
}

// ── Helpers ──────────────────────────────────────────────────────────────────

function slugify(text: string): string {
  return text.toLowerCase().replace(/[^a-z0-9]+/g, '-').replace(/^-|-$/g, '');
}

function tryPrettyJson(text: string): string {
  try {
    return JSON.stringify(JSON.parse(text), null, 2);
  } catch {
    return text;
  }
}

function escapeHtml(text: string): string {
  return text
    .replace(/&/g, '&amp;')
    .replace(/</g, '&lt;')
    .replace(/>/g, '&gt;')
    .replace(/"/g, '&quot;');
}
